### ISSUE TITLE
[US11] Como empledo  Quiero leer material educativo  Para informarme sobre cuestiones ambientales

### ISSUE THREAD

**Issue by bauticanavese** [bauticanavese/VerdeQueTeQuieroVerde#22]
- La vista previa muestra solo titulo, descripcion e imagen.
- Se puede abrir una vista completa que muestra toda la informacion

**Comment by edjus** [comment]
Por ahora se va a mostrar con una imagen pre-definida, cuando se resuelva la persistencia de imágenes habría que actualizarlo.
