### ISSUE TITLE
[US14] Como empleado  Quiero un espacio para proponer nuevas ideas de como cuidar nuestro planeta  Para involucrarme mas en el proyecto

### ISSUE THREAD

**Issue by bauticanavese** [bauticanavese/VerdeQueTeQuieroVerde#25]
- Vista (Segurencias) para enviar una opinion anonima acerca del proyecto.
- Solo se manda comentrario en texto plano por google form

**Comment by guillecondori** [comment]
Ver si es posible fixear el tamaño de la card de "ideas" a mi me aparece mas "alta" que las otras
