### ISSUE TITLE
[US19] Como voluntario Quiero capacitarme en temas ambientales  Para que las charlas sean un exito

### ISSUE THREAD

**Issue by bauticanavese** [bauticanavese/VerdeQueTeQuieroVerde#30]
- Proveer a los voluntarios de material ambiental para que puedan dar charlas
- Un archivo con lecturas recomendadas sobre el tema
- Consejos de como dar una charla exitosa (oratoria)

**Comment by guillecondori** [comment]
Guia en el drive del grupo https://docs.google.com/document/d/1Qz0idUfOaR2M5s93X0J7Fy4d4CDY4ADuUU6MOpQC8D4/edit#
