### ISSUE TITLE
[US20] Como voluntario Quiero ser capacitado en el uso de la web Para su buen uso y administración

### ISSUE THREAD

**Issue by bauticanavese** [bauticanavese/VerdeQueTeQuieroVerde#31]
- Capacitar a los administradores acerca del uso del sitio. 
- Realizar un manual de usuario simple para que se familiaricen con el sitio.

**Enlace al documento** [link](https://docs.google.com/document/d/1_oqr9klIC0M6EPSyLEXtba2QU9_X7MiLNIhRhw3XmBk/edit#)

**Comment by guillecondori** [comment]
muy bueno 👍
