### ISSUE TITLE
Persistencia de archivos multimedia

### ISSUE THREAD

**Issue by bauticanavese** [bauticanavese/VerdeQueTeQuieroVerde#43]
Objetivo: definir la manera en que van a ser persistidos los datos multimedia (tanto imagenes y videos). Tenemos dos opciones en mente: 
* Decodificar y guardarlo en la base de datos.
* Usar un servicio cloud (por ejemplo Firebase)

**Comment by edjus** [comment]
El método que se elija tiene que poder resolverse desde la administración de django.

**Comment by edjus** [comment]
Agrego un enlace que puede servir: https://www.dothedev.com/blog/heroku-django-store-your-uploaded-media-files-for-free/

**Comment by bauticanavese** [comment]
La manera de solucionar el problema rápidamente, es solicitar al voluntario mediante un `input text` la url a la imagen a subir, al crear material educativo. Leer de ese `input text` para luego guardarlo en la bdd. Se debe realizar una migración agregando el campo `img_url` para el material educativo.

Pros:  
* Sin involucrar de servicios cloud dentro del repo.
* No decodificar la imagen.
* Facil de implementar.
Cons:  
* Dependencia de un servicio externo, si esa url se cae o deja de existir, deberiamos buscar otra para reemplazarla.
